apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /webapp(/|$)(.*)
        pathType: Prefix
        backend:
          backend:
          serviceName: webapp
          servicePort: 80
